---
- name: Install Filebeat
  hosts: webservers
  become: true
  tasks:

    - name: Download the debian package files
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
        dest: /etc/filebeat.deb

    - name: Install the debian package
      apt:
        deb: /etc/filebeat.deb
        state: present

    - name: Copy the configuration file to the server
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable and configure the docker module
      command: filebeat modules enable system

    - name: Start Filebeat
      shell: |
        filebeat setup
        service filebeat start
