---
- name: Install Docker Metricbeat
  hosts: webservers
  become: true
  tasks:

    - name: Download the debian package files
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
        dest: /etc/metricbeat.deb

    - name: Install the debian package
      apt:
        deb: /etc/metricbeat.deb
        state: present

    - name: Copy the configuration file to the server
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure the docker module
      command: metricbeat modules enable docker

    - name: Start Metricbeat
      shell: |
        metricbeat setup
        metricbeat -e
